name: Build
on: [push, pull_request]

env:
  LEGACY_NDK: ${{ github.workspace }}/LEGACY_NDK/android-ndk-legacy

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          architecture: x64

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          pip install requests

      - name: Show workspace
        run: echo "Workspace path is:${{ github.workspace }}"

      - name: Download LEGACY_NDK
        run: | 
          cd .ci
          sh ndk_fortran.sh
          cd ..

      - name: Test env
        run: echo $LEGACY_NDK

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          workdir: src
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
