name: Build
on: [push, pull_request]

env:
  LEGACY_NDK: ${{ github.workspace }}/LEGACY_NDK/android-ndk-legacy

jobs:
  build-android:
    name: Build for Android
    if: contains(github.event.head_commit.message, '-all_tests')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show workspace
        run: echo "Workspace path is:${{ github.workspace }}"

      - name: Download LEGACY_NDK
        run: | 
          cd .ci
          sh ndk_fortran.sh
          cd ..

      - name: Test env
        run: echo $LEGACY_NDK

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: |
              pip uninstall cython
              pip install -U cython
              buildozer android debug
          workdir: src
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
